### ISSUE TITLE
[Request] Add documentation on specifics used to build

### ISSUE THREAD

**Issue by gcervantes8** [gwang-msft/unofficial_onnxruntime_mobile_releases#5]
### My issue
I'm having trouble recreating the provided mobile releases.

With this library, the run time I get is around 2.5 seconds with my model.
When I try to build my own mobile library, the run time is around 26-30 seconds.

I'm trying to get faster run time when I build it, but I'm not sure how.

### Building
I'm using version 1.10.0 of ONNXRunTime.
This is an example command that I run to build:

`./build.sh --android --android_sdk_path ~/Android/Sdk --android_ndk_path ~/Android/Sdk/ndk/23.1.7779620 --android_abi arm64-v8a --android_api 27 --skip_tests --build_java --minimal_build extended`

And the file that I use is: 
`onnxruntime/build/Android/Debug/java/build/android/outputs/aar/onnxruntime-release.aar`

Parameters I've modified to try and get faster run times:

- minimal_build parameter

- use_nnapi

---
Is there any place I can look to see how these libraries are built?
Any help would be appreciated!

**Comment by gwang-msft** [comment]
Have you tried build with `--config Release`? The default build config is `Debug`

**Comment by gcervantes8** [comment]
Thank you for the help! I started using `--config Release`, I didn't know it existed.

I realize now that I made a mistake when checking the run time of the library.  I was accidentally using a different input.  
After doing a fair comparison, I seem to be getting a similar running time.  So all is good!
